/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { RoleWhereUniqueInput } from "../../role/base/RoleWhereUniqueInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TimesheetCreateNestedManyWithoutUsersInput } from "./TimesheetCreateNestedManyWithoutUsersInput";
import { VacationPolicyCreateNestedManyWithoutUsersInput } from "./VacationPolicyCreateNestedManyWithoutUsersInput";
import { VacationRequestCreateNestedManyWithoutUsersInput } from "./VacationRequestCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => RoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoleWhereUniqueInput)
  @IsOptional()
  @Field(() => RoleWhereUniqueInput, {
    nullable: true,
  })
  role?: RoleWhereUniqueInput | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TimesheetCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TimesheetCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TimesheetCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  timesheets?: TimesheetCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => VacationPolicyCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VacationPolicyCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VacationPolicyCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  vacationPolicies?: VacationPolicyCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => VacationRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VacationRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VacationRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  vacationRequests?: VacationRequestCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
