/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { RoleWhereUniqueInput } from "../../role/base/RoleWhereUniqueInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TimesheetUpdateManyWithoutUsersInput } from "./TimesheetUpdateManyWithoutUsersInput";
import { VacationPolicyUpdateManyWithoutUsersInput } from "./VacationPolicyUpdateManyWithoutUsersInput";
import { VacationRequestUpdateManyWithoutUsersInput } from "./VacationRequestUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => RoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoleWhereUniqueInput)
  @IsOptional()
  @Field(() => RoleWhereUniqueInput, {
    nullable: true,
  })
  role?: RoleWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TimesheetUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TimesheetUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TimesheetUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  timesheets?: TimesheetUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => VacationPolicyUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VacationPolicyUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VacationPolicyUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  vacationPolicies?: VacationPolicyUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => VacationRequestUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VacationRequestUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VacationRequestUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  vacationRequests?: VacationRequestUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
