/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { RoleWhereUniqueInput } from "../../role/base/RoleWhereUniqueInput";
import { TimesheetListRelationFilter } from "../../timesheet/base/TimesheetListRelationFilter";
import { VacationPolicyListRelationFilter } from "../../vacationPolicy/base/VacationPolicyListRelationFilter";
import { VacationRequestListRelationFilter } from "../../vacationRequest/base/VacationRequestListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoleWhereUniqueInput)
  @IsOptional()
  @Field(() => RoleWhereUniqueInput, {
    nullable: true,
  })
  role?: RoleWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => TimesheetListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TimesheetListRelationFilter)
  @IsOptional()
  @Field(() => TimesheetListRelationFilter, {
    nullable: true,
  })
  timesheets?: TimesheetListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => VacationPolicyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VacationPolicyListRelationFilter)
  @IsOptional()
  @Field(() => VacationPolicyListRelationFilter, {
    nullable: true,
  })
  vacationPolicies?: VacationPolicyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => VacationRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VacationRequestListRelationFilter)
  @IsOptional()
  @Field(() => VacationRequestListRelationFilter, {
    nullable: true,
  })
  vacationRequests?: VacationRequestListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
