/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { VacationRequest } from "./VacationRequest";
import { VacationRequestCountArgs } from "./VacationRequestCountArgs";
import { VacationRequestFindManyArgs } from "./VacationRequestFindManyArgs";
import { VacationRequestFindUniqueArgs } from "./VacationRequestFindUniqueArgs";
import { CreateVacationRequestArgs } from "./CreateVacationRequestArgs";
import { UpdateVacationRequestArgs } from "./UpdateVacationRequestArgs";
import { DeleteVacationRequestArgs } from "./DeleteVacationRequestArgs";
import { User } from "../../user/base/User";
import { VacationRequestService } from "../vacationRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => VacationRequest)
export class VacationRequestResolverBase {
  constructor(
    protected readonly service: VacationRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "read",
    possession: "any",
  })
  async _vacationRequestsMeta(
    @graphql.Args() args: VacationRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VacationRequest])
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "read",
    possession: "any",
  })
  async vacationRequests(
    @graphql.Args() args: VacationRequestFindManyArgs
  ): Promise<VacationRequest[]> {
    return this.service.vacationRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VacationRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "read",
    possession: "own",
  })
  async vacationRequest(
    @graphql.Args() args: VacationRequestFindUniqueArgs
  ): Promise<VacationRequest | null> {
    const result = await this.service.vacationRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VacationRequest)
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "create",
    possession: "any",
  })
  async createVacationRequest(
    @graphql.Args() args: CreateVacationRequestArgs
  ): Promise<VacationRequest> {
    return await this.service.createVacationRequest({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VacationRequest)
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "update",
    possession: "any",
  })
  async updateVacationRequest(
    @graphql.Args() args: UpdateVacationRequestArgs
  ): Promise<VacationRequest | null> {
    try {
      return await this.service.updateVacationRequest({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VacationRequest)
  @nestAccessControl.UseRoles({
    resource: "VacationRequest",
    action: "delete",
    possession: "any",
  })
  async deleteVacationRequest(
    @graphql.Args() args: DeleteVacationRequestArgs
  ): Promise<VacationRequest | null> {
    try {
      return await this.service.deleteVacationRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: VacationRequest
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VacationRequest)
  async ApproveVacationRequest(
    @graphql.Args()
    args: VacationRequest
  ): Promise<VacationRequest> {
    return this.service.ApproveVacationRequest(args);
  }

  @graphql.Mutation(() => VacationRequest)
  async RejectVacationRequest(
    @graphql.Args()
    args: VacationRequest
  ): Promise<VacationRequest> {
    return this.service.RejectVacationRequest(args);
  }
}
